AllCops:
  Exclude:
    - 'spec/support/test_app/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - vendor/bundle/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

