AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/support/test_app/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 99

Metrics/MethodLength:
  CountComments: false
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/PredicateName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true
